### ISSUE TITLE
Next event: please fix mobile!

### ISSUE THREAD

**Issue by franklouwers** [cfgmgmtcamp/cfgmgmtcamp.eu#36]
## Basic Information

* [x] : Visual issue (please mention your platform/browser)

On all screens smaller than 800 pixels, regardless of platform/browser, the schedule doesn't work.

## Description:

On all screens smaller than 800 pixels, regardless of platform/browser, the schedule doesn't work. This is just not tested, which is a shame. What do people do at conferences? Look up the schedule. What do they use? Their mobile.

I get the "just submit a PR" argument, but to be honest, that's ridiculous. This conference (and LOADays) suffers from a "not invented here" problem that the organisers should seriously consider fixing. Either by having experienced in UI/web-UX/CSS/JS fix the current stuff, or move to a ready-made platform. A quick search on gh show me there are multiple open source ones - https://github.com/search?o=desc&q=conference+schedule&s=stars&type=Repositories

At least for this conference, I didn't have to create an account on somebodies private git-server that can't send out mail...
&lt;/rant&gt;

**Comment by jpmens** [comment]
The only bit of text worth keeping in this ticket is

> the schedule doesn't work

As I have personally told Tosh and Kris, what they now have is, put mildly a train wreck and a shame for a) the industry and b) for the effort both of them are investing in these conferences.

I explicitly applaud exactly that effort, and have tried argumenting that the rest should be an experience worthy of open source conference visitors, which it is not currently. To add insult to injury, several people told me there's an app (iggly  something) which solves all the problems, but that works on Android only.

And I will refraid from writing here what I said about the suggestion to _just submit a PR_.

I've heard good things from

- https://pretalx.com/p/about/
- https://frab.github.io/frab/

Instead of my nagging, I will put my money where my mouth is and see if I can assist in getting one of these working in the spirit of how I would do it for LOADays. 

The organizers may then decide whether they wish to take on the result or rather not.

**Comment by franklouwers** [comment]
👍
